### ISSUE TITLE
The icon on the navigation bar is wrong size and blurry when scale factor is fraction

### ISSUE THREAD

**Issue by XCYRKDSDA** [madskristensen/MarkdownEditor2022#30]
**Describe the bug**
I'm using Visual Studio 2022 on a 4K monitor. When scale factor is set to 100% and 200%, everything looks good. But when it's set to 125%, 150% or 175%, the icon on the navigation bar is rendered too big and blurry.
- 175%:
![image](https://user-images.githubusercontent.com/46109762/158137967-ef9a6a1b-141c-4287-90a9-ed85584bc4af.png)
- 150% :
![image](https://user-images.githubusercontent.com/46109762/158140259-88eef5a9-8374-4114-8a01-f46cccc99dd4.png)
- 125%:
![image](https://user-images.githubusercontent.com/46109762/158140427-ce7b9e33-4338-47f1-b160-97a23f321008.png)

**To Reproduce**
1. Set system display scale factor to a fraction value
2. Launch Visual Studio after the setup
3. Open a markdown file in Visual Studio

**Expected behavior**
Clear and correctly sized navigation icon when scale factor is fraction.

**Screenshots**
See description above.

**Comment by madskristensen** [comment]
@gundermanc does this particular icon not support high DPI or is it all icons in the navigational dropdown bars that don't? I use icon glyph 126 here https://github.com/madskristensen/MarkdownEditor2022/blob/master/src/Editor/DropdownBars.cs#L102

**Comment by gundermanc** [comment]
@madskristensen the problem is that you are using the 'Managed Languages Framework' (Microsoft.VisualStudio.Package.LanguageService.15.0.dll) TypeAndMemberDropdownBars type to populate the navbar. This type is rendering images from an 'image list' constructed from pre-rendered fixed-size bitmap that ships with the MLF.

In recent years most first party features have moved away from using image lists and use 'Image Monikers' instead, which are automatically scaled using multiple image assets, or scalable graphics.

# The Fix
The minimal fix is probably to implement [IVsDropdownBarClient4](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.textmanager.interop.ivsdropdownbarclient4?view=visualstudiosdk-2022) on DropDownBars object and implement [GetEntryImage()](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.textmanager.interop.ivsdropdownbarclient4.getentryimage?view=visualstudiosdk-2022#microsoft-visualstudio-textmanager-interop-ivsdropdownbarclient4-getentryimage(system-int32-system-int32)) to return an ImageMoniker from [KnownMonikers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.imaging.knownmonikers?view=visualstudiosdk-2022).

KnownMonikers are usually guaranteed to scale.

e.g.:

```csharp
public ImageMoniker GetEntryImage(int iCombo, int iIndex)
{
    return KnownMonikers.File;
}
```

# Explanation
Under the hood, Drop Down Bars are driven by IVsDropDownClient COM interface. The TypeAndMemberDropdownBars type used by this extension is just a wrapper around the actual interface. In this case it's an incomplete wrapper that implements only the DPI-unaware way of providing images.

# Recommendations
I generally recommend making a concerted effort to remove 'MLF' and any other sort of framework over the VS API from your codebase. Most such abstractions are quite old and often have performance or experience caveats. State of the art is typically:

- Use language server client protocol
- Fill in the gaps with MEF editor APIs
- Fill in the gaps with IVs* APIs.

**Comment by madskristensen** [comment]
@gundermanc thank you, thank you. It works beautifully.
