### ISSUE TITLE
Support of Markdown linting

### ISSUE THREAD

**Issue by skovalyova** [madskristensen/MarkdownEditor2022#42]
Hello there. Thanks for the great extension, it's a real timesaver!

Previously, I've been working with similar functionality provided by VS Code. The functionality I really miss is **markdown linting**, similar to this VS Code extension:
https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint

It does live highlighting for rule violations, and enforces consistent style for Markdown files so they look very accurate. I would be glad to see this functionality because there is no similar tooling for Visual Studio so far. Currently, I have to use both Visual Studio and VS Code extensions to write markdown files and to fix formatitng.

**Comment by madskristensen** [comment]
A few of the rules from that extension is built in to the VS version. What particular rules do you miss?

**Comment by madskristensen** [comment]
@skovalyova ping

**Comment by madskristensen** [comment]
Closing due to lack of clarification

**Comment by alexandrejobin** [comment]
I would add my vote to support linting. The markdownlint project seems to be a good one to use since that it force you to follow rules and you can add your own rules. If you want to know which rules I personally use, I would say all of them. It helped me a lot to make good formatted doc and to understand why the rendered version wasn't like I wanted.

We already have .editorconfig to help standardize the code, it would be nice to have something similar to standardize the markdown files in my opinion.

**Comment by Thieum** [comment]
I would add my vote too - I open my markdown files in vs code after working with them in VS2022 for this reason. The linting gives good insights on what could be improved in the document, and the auto-formatting of arrays and other parts of the document that could be tedious to improve manually is pretty good.
